azs:
- name: z1
  cloud_properties:
    availability_zone: nova

vm_types:
- name: minimal
  cloud_properties:
    instance_type: m1.small
- name: default 
  cloud_properties:
    instance_type: m1.medium
- name: small
  cloud_properties:
    instance_type: m1.small
- name: medium
  cloud_properties:
    instance_type: m1.medium
- name: medium-memory-8GB
  cloud_properties:
    instance_type: m1.medium
- name: large
  cloud_properties:
    instance_type: m1.large
- name: xlarge
  cloud_properties:
    instance_type: m1.xlarge
- name: small-50GB
  cloud_properties:
    instance_type: m1.medium
- name: small-50GB-ephemeral-disk 
  cloud_properties:
    instance_type: m1.medium
- name: small-100GB-ephemeral-disk
  cloud_properties:
    instance_type: m1.large
- name: small-highmem-100GB-ephemeral-disk 
  cloud_properties:
    instance_type: m1.large
- name: small-highmem-16GB
  cloud_properties:
    instance_type: m1.large
- name: service_medium
  cloud_properties:
    instance_type: m1.medium
- name: service_medium_2G
  cloud_properties:
    instance_type: m1.medium
- name: portal_small
  cloud_properties:
    instance_type: m1.small
- name: portal_medium
  cloud_properties:
    instance_type: m1.small
- name: portal_large
  cloud_properties:
    instance_type: m1.small

compilation:
  az: z3
  network: default
  reuse_compilation_vms: true
  vm_type: large
  workers: 3

disk_types:
- disk_size: 1024
  name: default
- disk_size: 1024
  name: 1GB
- disk_size: 2048
  name: 2GB
- disk_size: 4096
  name: 4GB
- disk_size: 5120
  name: 5GB
- disk_size: 8192
  name: 8GB
- disk_size: 10240
  name: 10GB
- disk_size: 20480
  name: 20GB
- disk_size: 30720
  name: 30GB
- disk_size: 51200
  name: 50GB
- disk_size: 102400
  name: 100GB
- disk_size: 1048576
  name: 1TB
- cloud_properties:
    type: SSD1 
  disk_size: 2000
  name: 2GB_GP2
- cloud_properties:
    type: SSD1 
  disk_size: 5000
  name: 5GB_GP2
- cloud_properties:
    type: SSD1 
  disk_size: 10000
  name: 10GB_GP2
- cloud_properties:
    type: SSD1 
  disk_size: 50000
  name: 50GB_GP2

networks:
- name: default
  type: manual
  subnets:
  - az: z1
    cloud_properties:
      name: 192.168.120.0
      net_id: a2ac14b9-2e90-4bae-83aa-f5f3bb54f53e
      network_address: 192.168.120.0
      network_name: "EXTERNAL0"
      security_groups:
      - ALL
    dns:
    - 8.8.8.8
    gateway: 192.168.120.254
    range: 192.168.120.0/24
    reserved: # Cloudit V5.0 에서 사용하지 않는 대역
    - 192.168.120.1 - 192.168.120.9
    - 192.168.120.51 - 192.168.120.254
    static: # VM 배포시 고정 IP 를 부여하는 경우 사용하는 대역
    - 192.168.120.11 - 192.168.120.15
    - 192.168.120.30 - 192.168.120.30

- name: vip
  type: vip

vm_extensions:
- cloud_properties:
    ports:
    - host: 3306
  name: mysql-proxy-lb
- name: cf-router-network-properties
- name: cf-tcp-router-network-properties
- name: diego-ssh-proxy-network-properties
- name: cf-haproxy-network-properties 
- cloud_properties:
    ephemeral_disk:
      size: 51200
      type: gp2
  name: small-50GB 
- cloud_properties:
    ephemeral_disk:
      size: 102400
      type: gp2
  name: small-highmem-100GB
- name: ssh-proxy-and-router-lb
  cloud_properties:
    ports:
    - host: 80
    - host: 443
    - host: 2222
    - host: 4443
